/*
 * t_tokgen.c -- host unit tests for include/buffalo/buf_tokgen.h.
 *
 * Plain `cc`, no cccc. The oracle is the real validator: every header the
 * generator emits must pass buf_tc_check against the spec it came from --
 * the same check the comptime pass runs on a checked-in header.
 */
#include <stdio.h>
#include <string.h>

#include "buf_rx.h"
#include "buf_tokcheck.h"
#include "buf_tokgen.h"

static int failures = 0;
static int checks   = 0;

#define CHECK(cond, what)                                                     \
    do {                                                                     \
        checks++;                                                            \
        if (!(cond)) {                                                       \
            failures++;                                                      \
            printf("FAIL %s:%d  %s\n", __FILE__, __LINE__, (what));          \
        }                                                                    \
    } while (0)

static BufRx rx;
static BufTg tg;
static BufTc tc;

/* Generate a header for a spec file and validate it with the real checker.
 * Returns 1 on pass; self-reports on failure. */
static int roundtrip_file(const char *path) {
    checks++;
    if (buf_rx_read_file(&rx, path) != 0) {
        printf("FAIL %s:%d  %s: %s\n", __FILE__, __LINE__, path, rx.error);
        failures++;
        return 0;
    }
    if (buf_tokgen_emit(&tg, &rx) != 0) {
        printf("FAIL %s:%d  %s: %s\n", __FILE__, __LINE__, path, tg.error);
        failures++;
        return 0;
    }
    if (buf_tc_load_string(&tc, "<generated>", tg.out) != 0 ||
        buf_tc_check(&tc, &rx) != 0) {
        printf("FAIL %s:%d  generated header rejected: %s\n", __FILE__,
               __LINE__, tc.error);
        failures++;
        return 0;
    }
    return 1;
}

int main(void) {
    /* every spec in the suite round-trips through the real validator */
    static const char *SPECS[] = {
        "examples/digits.bflo", "examples/calc.bflo", "examples/clike.bflo",
        "examples/json.bflo",   "examples/expr.bflo",
    };
    size_t i;

    for (i = 0; i < sizeof(SPECS) / sizeof(*SPECS); i++)
        CHECK(roundtrip_file(SPECS[i]) == 1, "generated header validates");

    /* provenance, guard derivation, reserved slots */
    CHECK(buf_rx_read_file(&rx, "examples/calc.bflo") == 0, "calc.bflo reads");
    CHECK(buf_tokgen_emit(&tg, &rx) == 0, "calc.bflo emits");
    CHECK(strstr(tg.out, "Generated by `buffalo tokens` from "
                         "examples/calc.bflo -- do not edit.") != NULL,
          "provenance comment present");
    CHECK(strstr(tg.out, "#ifndef CALC_TOKENS_H\n") != NULL,
          "guard derived from the spec base name");
    CHECK(strstr(tg.out, "#endif /* CALC_TOKENS_H */\n") != NULL,
          "guard closed");
    CHECK(strstr(tg.out, "enum {\n    TOK_EOF = 0, TOK_ERROR = 1") != NULL,
          "reserved slots pinned and first");
    CHECK(strstr(tg.out, "TOK_INT") != NULL && strstr(tg.out, "TOK_RPAREN") != NULL,
          "user kinds present");

    /* a leading digit in the base name gets a '_' prefix */
    CHECK(buf_rx_parse_string(&rx, "1234.bflo",
                              "%tokens X\nX \"x\"\n") == 0,
          "digit-named spec parses");
    CHECK(buf_tokgen_emit(&tg, &rx) == 0, "digit-named spec emits");
    CHECK(strstr(tg.out, "#ifndef _1234_TOKENS_H\n") != NULL,
          "leading digit folded into a valid guard");

    /* many kinds: the wrapped enum must still validate */
    {
        char spec[2048];
        int  n;
        n = snprintf(spec, sizeof(spec), "%s", "%tokens");
        for (i = 0; i < 30; i++)
            n += snprintf(spec + n, sizeof(spec) - (size_t)n, " T%02zu", i);
        n += snprintf(spec + n, sizeof(spec) - (size_t)n, "\n");
        for (i = 0; i < 30; i++)
            n += snprintf(spec + n, sizeof(spec) - (size_t)n,
                          "T%02zu \"x\"\n", i);
        CHECK(buf_rx_parse_string(&rx, "<wide>", spec) == 0,
              "30-kind spec parses");
        CHECK(buf_tokgen_emit(&tg, &rx) == 0, "30-kind spec emits");
        CHECK(buf_tc_load_string(&tc, "<generated>", tg.out) == 0 &&
                  buf_tc_check(&tc, &rx) == 0,
              "wrapped 30-kind header validates");
        if (tc.has_error) printf("  -> %s\n", tc.error);
    }

    /* the emitted text always fits the checker's own load limit */
    CHECK(tg.out_len < BUF_TC_SRC_MAX, "emitted text under BUF_TC_SRC_MAX");

    printf("%s: %d checks, %d failures\n",
           failures ? "FAIL" : "ok  ", checks, failures);
    return failures ? 1 : 0;
}
