/*
 * big_tokens.h -- checked in; the comptime pass validates this against
 * examples/big.bflo (%tokens list and order) and errors on drift.
 *
 * TOK_EOF = 0 and TOK_ERROR = 1 are reserved (see BUF_TOK_* in buf_rt.h).
 * The remaining constants follow big.bflo's %tokens line, in order. big.bflo is a
 * measurement fixture for the M3 spike (docs/performance.md), not a worked
 * example -- see examples/clike.bflo for that.
 */
#ifndef BIG_TOKENS_H
#define BIG_TOKENS_H

enum {
    TOK_EOF = 0, TOK_ERROR = 1,

    TOK_KW_AUTO, TOK_KW_BREAK, TOK_KW_CASE, TOK_KW_CHAR, TOK_KW_CONST,
    TOK_KW_CONTINUE, TOK_KW_DEFAULT, TOK_KW_DO, TOK_KW_DOUBLE, TOK_KW_ELSE,
    TOK_KW_ENUM, TOK_KW_EXTERN, TOK_KW_FLOAT, TOK_KW_FOR, TOK_KW_GOTO,
    TOK_KW_IF, TOK_KW_INLINE, TOK_KW_INT, TOK_KW_LONG, TOK_KW_REGISTER,
    TOK_KW_RESTRICT, TOK_KW_RETURN, TOK_KW_SHORT, TOK_KW_SIGNED, TOK_KW_SIZEOF,
    TOK_KW_STATIC, TOK_KW_STRUCT, TOK_KW_SWITCH, TOK_KW_TYPEDEF, TOK_KW_UNION,
    TOK_KW_UNSIGNED, TOK_KW_VOID, TOK_KW_VOLATILE, TOK_KW_WHILE, TOK_KW_BOOL,
    TOK_KW_COMPLEX, TOK_KW_IMAGINARY, TOK_KW_ALIGNAS, TOK_KW_ALIGNOF,
    TOK_KW_ATOMIC, TOK_KW_GENERIC, TOK_KW_NORETURN, TOK_KW_STATICASSERT,
    TOK_KW_THREADLOCAL,

    TOK_IDENT,
    TOK_HEXFLOAT, TOK_FLOAT, TOK_HEXINT, TOK_BININT, TOK_OCTINT, TOK_DECINT,
    TOK_STRING, TOK_CHARLIT,

    TOK_ELLIPSIS, TOK_SHL_ASSIGN, TOK_SHR_ASSIGN, TOK_ARROW, TOK_INCR,
    TOK_DECR, TOK_SHL, TOK_SHR, TOK_LE, TOK_GE, TOK_EQ, TOK_NE, TOK_ANDAND,
    TOK_OROR, TOK_PLUS_ASSIGN, TOK_MINUS_ASSIGN, TOK_STAR_ASSIGN,
    TOK_SLASH_ASSIGN, TOK_PCT_ASSIGN, TOK_AMP_ASSIGN, TOK_PIPE_ASSIGN,
    TOK_CARET_ASSIGN, TOK_PLUS, TOK_MINUS, TOK_STAR, TOK_SLASH, TOK_PERCENT,
    TOK_ASSIGN, TOK_LT, TOK_GT, TOK_NOT, TOK_AMP, TOK_PIPE, TOK_CARET,
    TOK_TILDE, TOK_QUESTION, TOK_COLON, TOK_SEMI, TOK_COMMA, TOK_DOT,
    TOK_LPAREN, TOK_RPAREN, TOK_LBRACE, TOK_RBRACE, TOK_LBRACKET,
    TOK_RBRACKET, TOK_HASH
};

#endif /* BIG_TOKENS_H */
