/*
 * buf_tokgen.c -- definitions for buf_tokgen.h (render a spec's %tokens list
 * as a <name>_tokens.h header).
 *
 * Host-only module: linked into the buf_tokgen tool and the t_tokgen host
 * test under a plain `cc` beside buf_rx.c. It never runs inside cccc's
 * comptime VM, so unlike buf_rx/buf_tokcheck it may use <string.h> freely.
 */
#include "buf_tokgen.h"

#include <stdio.h>
#include <string.h>

static void buf_tg_err(BufTg *tg, const char *msg) {
    if (tg->has_error) return;
    snprintf(tg->error, sizeof(tg->error), "%s", msg);
    tg->has_error = 1;
}

/* Append n bytes, first-wins on overflow. out_len stays < BUF_TG_OUT_MAX on
 * every success path, so the caller's trailing NUL write is in bounds. */
static void buf_tg_put(BufTg *tg, const char *s, int n) {
    int i;
    if (tg->has_error) return;
    if (tg->out_len + n >= BUF_TG_OUT_MAX) {
        buf_tg_err(tg, "generated header text too large");
        return;
    }
    for (i = 0; i < n; i++) tg->out[tg->out_len++] = s[i];
}

static void buf_tg_puts(BufTg *tg, const char *s) {
    buf_tg_put(tg, s, (int)strlen(s));
}

static void buf_tg_putc(BufTg *tg, char c) {
    buf_tg_put(tg, &c, 1);
}

/* examples/calc.bflo -> CALC_TOKENS_H: base name, trailing ".bflo" stripped,
 * non-alphanumeric bytes folded to '_', uppercased, "_TOKENS_H" appended. A
 * leading digit gets a '_' prefix so the guard stays a valid macro name. */
static void buf_tg_guard(const BufRx *rx, char *out, int cap) {
    const char *p     = rx->spec_path ? rx->spec_path : "";
    const char *base  = p, *q = p;
    const char *suffix = "_TOKENS_H";
    int         n = 0, k = 0, i;

    while (q[n]) { if (q[n] == '/') base = q + n + 1; n++; }
    n = (int)(q + n - base);
    if (n >= 5 && strncmp(base + n - 5, ".bflo", 5) == 0) n -= 5;

    if (n > 0 && buf_rx_is_digit((unsigned char)base[0]) && k < cap - 1)
        out[k++] = '_';
    for (i = 0; i < n && k < cap - (int)strlen(suffix) - 1; i++) {
        char c = base[i];
        if (buf_rx_is_alpha((unsigned char)c))      out[k++] = (char)(c & ~0x20);
        else if (buf_rx_is_digit((unsigned char)c)) out[k++] = c;
        else                                        out[k++] = '_';
    }
    strcpy(out + k, suffix);
}

int buf_tokgen_emit(BufTg *tg, const BufRx *rx) {
    char guard[BUF_RX_NAME_MAX + 32];
    int  i, col;

    tg->out_len   = 0;
    tg->error[0]  = '\0';
    tg->has_error = 0;

    if (rx->token_count == 0) {
        buf_tg_err(tg, "spec has no %tokens entries");
        return -1;
    }

    buf_tg_guard(rx, guard, sizeof(guard));

    buf_tg_puts(tg, "/*\n"
                    " * Generated by `buffalo tokens` from ");
    buf_tg_puts(tg, rx->spec_path ? rx->spec_path : "<spec>");
    buf_tg_puts(tg, " -- do not edit.\n"
                    " *\n"
                    " * TOK_EOF = 0 and TOK_ERROR = 1 are reserved (see BUF_TOK_*\n"
                    " * in buf_rt.h). The remaining constants follow the spec's\n"
                    " * %tokens line, in order.\n"
                    " */\n"
                    "#ifndef ");
    buf_tg_puts(tg, guard);
    buf_tg_puts(tg, "\n#define ");
    buf_tg_puts(tg, guard);
    buf_tg_puts(tg, "\n\nenum {\n    TOK_EOF = 0, TOK_ERROR = 1");

    /* user kinds, comma-separated, wrapped at column 76 (a comma lands at
     * the end of the previous line; the continuation line re-indents). The
     * comma before the first user kind separates it from TOK_ERROR = 1. */
    col = 30;
    for (i = 0; i < rx->token_count; i++) {
        const char *nm   = rx->tokens[i];
        int         klen = 4 + (int)strlen(nm); /* "TOK_" + name */
        buf_tg_putc(tg, ',');
        col++;
        if (col + 1 + klen > 76) {
            buf_tg_putc(tg, '\n');
            buf_tg_puts(tg, "    ");
            col = 4;
        } else {
            buf_tg_putc(tg, ' ');
            col++;
        }
        buf_tg_puts(tg, "TOK_");
        buf_tg_puts(tg, nm);
        col += klen;
    }
    buf_tg_puts(tg, "\n};\n\n#endif /* ");
    buf_tg_puts(tg, guard);
    buf_tg_puts(tg, " */\n");

    if (tg->has_error) return -1;
    tg->out[tg->out_len] = '\0';
    return 0;
}
